name: tracers
channels:
  - conda-forge
  - default
dependencies:
  - python=3.6
  - numpy
  - scipy
  - pandas
  - dask
  - xarray
  - matplotlib
  - jupyter
  - pip:
    - git+https://github.com/raphaeldussin/easy_coloc
